new_parent/MBF/urls.py
from django.conf.urls import url
from . import views

app_name = 'MBF'
urlpatterns = [
    url(r'^$', views.dashboard, name='MBF-dashboard'),
    url(r'^home/$', views.home, name='MBF-home'),
    url(r'^create-account/$', views.create_user, name="create-account" ),
    url(r'^add-child/$', views.create_child, name="create-child" ),
    url(r'^add-caretaker/$', views.create_caretaker, name="create-caretaker" ),
    url(r'^add-event/(?P<event_type>[a-z]+)$', views.add_event, name="add-event" ),
    ## FIXME: Abstract out charts per event type
    url(r'^bottle-chart$', views.bottle_chart, name="bottle-chart" ),
]

new_parent/new_parent/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers
from MBF.api import UserViewSet, BottleFedViewSet, BabyViewSet, FamilyViewSet

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'family', FamilyViewSet)
router.register(r'baby', BabyViewSet)
router.register(r'bottle', BottleFedViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^MBF/', include('MBF.urls')),
    url(r'^$', 'MBF.views.home', name='home'),
    url(r'^admin/', admin.site.urls),
]

new_parent/MBF/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField


class Family(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

class CareTaker(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    family = models.ForeignKey(Family, on_delete=models.SET_NULL, null=True)
    phone_number = PhoneNumberField()
    relation_choices = (('PA', 'Parent'),
                        ('FA', 'Family'),
                        ('FR', 'Friend'),
                        ('NA', 'Nanny'))
    relation = models.CharField(max_length=2,
                                choices=relation_choices,
                                default='PA')

    def __str__(self):
        return str(self.user)

class Baby(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    birth_date = models.DateField(auto_now=False, auto_now_add=False)
    family = models.ForeignKey(Family, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.first_name

    def get_breast_events(self):
        eventList = BreastFed.objects.filter(baby=self).order_by('-event_time')[0:3]
        return eventList
    def get_bottle_events(self):
        eventList = BottleFed.objects.filter(baby=self).order_by('-event_time')[0:3]
        return eventList
    def get_temperature_events(self):
        eventList = Temperature.objects.filter(baby=self).order_by('-event_time')[0:3]
        return eventList
    def get_sleep_events(self):
        eventList = Sleep.objects.filter(baby=self).order_by('-event_time')[0:3]
        return eventList
    def get_wake_events(self):
        eventList = Wake.objects.filter(baby=self).order_by('-event_time')[0:3]
        return eventList
    def get_diaper_events(self):
        eventList = DiaperStatus.objects.filter(baby=self).order_by('-event_time')[0:3]
        return eventList


class BabyEvent(models.Model):
    event_time = models.DateTimeField(auto_now_add=True)
    baby = models.ForeignKey(Baby, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.event_time)

class BreastFed(BabyEvent):
    breast_choice = (('left', 'Left'),
                     ('right', 'Right'))
    breast = models.CharField(max_length=5,
                              choices=breast_choice,
                              default='left')

    def __str__(self):
        return str(self.event_time)

class BottleFed(BabyEvent):
    amount = models.PositiveSmallIntegerField()

    def __str__(self):
        return str(self.amount)

class DiaperStatus(BabyEvent):
    diaper_choice = (('poo', 'Poo'),
                     ('pee', 'Pee'),
                     ('poo & pee', 'Poo & Pee'))
    diaper = models.CharField(max_length=9,
                              choices=diaper_choice,
                              default='pee')

class Temperature(BabyEvent):
    temp_choice = (('normal', 'Normal'),
                   ('warm', 'Warm'),
                   ('hot', 'Hot'))
    temp = models.CharField(max_length=6,
                              choices=temp_choice,
                              default='normal')

class Sleep(BabyEvent):
    nap = 'NP'
    night = 'NT'
    sleep_choice = ((nap, 'Nap'),
                    (night, 'Night'))
    sleep_status = models.CharField(max_length=2,
                              choices=sleep_choice,
                              default=night)

class Wake(BabyEvent):
    # sleep_event = models.OneToOneField(Sleep, on_delete=models.CASCADE)
    nap = 'NP'
    night = 'NT'
    wake_choice = ((nap, 'Nap'),
                   (night, 'Night'))
    wake_status = models.CharField(max_length=2,
                              choices=wake_choice,
                              default=night)

new_parent/MBF/forms.py
from django import forms
from .models import CareTaker, Baby, BreastFed, BottleFed, DiaperStatus, Temperature, Sleep, Wake, Family
from django.contrib.auth.models import User

class CreateUserForm(forms.ModelForm):
    def save(self, commit=True):
        user = super(CreateUserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'password', 'first_name', 'last_name', 'email']
        widgets = {
            'password': forms.TextInput(attrs={'type': 'password'}),
        }

class CareTakerForm(forms.ModelForm):
    class Meta:
        model = CareTaker
        fields = ['phone_number', 'relation']
        labels = {
            'phone_number': 'Phone (+1-234-555-5555)'
        }

class CreateFamilyForm(forms.ModelForm):
    class Meta:
        model = Family
        fields = ['name']
        labels = {
            'name': 'Family Name'
        }

class BabyForm(forms.ModelForm):
    class Meta:
        model = Baby
        fields = ['first_name', 'last_name', 'birth_date', 'family']
        labels = {
            'birth_date': 'Birthday (mm/dd/yyyy)'
        }

class BreastFedForm(forms.ModelForm):
    class Meta:
        model = BreastFed
        fields = {'breast'}

class BottleFedForm(forms.ModelForm):
    class Meta:
        model = BottleFed
        fields = {'amount'}
        labels = {
            'amount': 'Amount (fl. oz.)'
        }

class DiaperStatusForm(forms.ModelForm):
    class Meta:
        model = DiaperStatus
        fields = {'diaper'}

class TemperatureForm(forms.ModelForm):
    class Meta:
        model = Temperature
        fields = {'temp'}

class SleepForm(forms.ModelForm):
    class Meta:
        model = Sleep
        fields = {'sleep_status'}

class WakeForm(forms.ModelForm):
    class Meta:
        model = Wake
        fields = {'wake_status'}

new_parent/MBF/views.py
import pytz
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseServerError
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from chartit import DataPool, Chart
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import CareTaker, BreastFed, BottleFed, DiaperStatus, Temperature, Sleep, Wake, Baby
from .forms import CreateUserForm, CareTakerForm, BabyForm, BreastFedForm, \
                   BottleFedForm, DiaperStatusForm, TemperatureForm, SleepForm, \
                   WakeForm, CreateFamilyForm

@login_required
def dashboard(request):
    care_taker = CareTaker.objects.get(user=request.user)
    babys = care_taker.family.baby_set.all()
    context = {'babys': babys}
    return render(request, 'MBF/dashboard.html', context)

def home(request):
    context = {}
    return render(request, 'MBF/home.html', context)

def create_user(request):
    if request.method == 'POST':
        caretaker_form = CareTakerForm(request.POST)
        user_form = CreateUserForm(request.POST)
        family_form = CreateFamilyForm(request.POST)
        if user_form.is_valid() and caretaker_form.is_valid() and family_form.is_valid():
            user = user_form.save()
            family = family_form.save()
            phone = caretaker_form.cleaned_data['phone_number']
            relation = caretaker_form.cleaned_data['relation']
            caretaker = CareTaker.objects.create(user=user, family=family, phone_number=phone, relation=relation)
            return HttpResponseRedirect('/login/')
    else:
        caretaker_form = CareTakerForm()
        family_form = CreateFamilyForm()
        user_form = CreateUserForm()


    return render(request, 'MBF/create_user.html',
                 {'caretaker_form': caretaker_form,
                  'user_form': user_form,
                  'family_form': family_form})

@login_required
def create_child(request):
    baby_form = BabyForm(request.POST)
    if baby_form.is_valid():
        baby = baby_form.save()
        return HttpResponseRedirect('/MBF/')

    return render(request, 'MBF/create_baby.html', {'baby_form': baby_form})

def create_caretaker(request):
        caretaker_form = CareTakerForm(request.POST)
        user_form = CreateUserForm(request.POST)
        if caretaker_form.is_valid() and user_form.is_valid():
            user = user_form.save()
            current_ct = CareTaker.objects.get(user=request.user)
            family = current_ct.family
            phone = caretaker_form.cleaned_data['phone_number']
            relation = caretaker_form.cleaned_data['relation']
            caretaker = CareTaker.objects.create(user=user, family=family, phone_number=phone, relation=relation)
            return HttpResponseRedirect('/MBF/')

        return render(request, 'MBF/create_caretaker.html', {'caretaker_form': caretaker_form,
                                                             'user_form': user_form})

@login_required
def add_event(request, event_type):
    event_form_list = {'breast': BreastFedForm,
                       'bottle': BottleFedForm,
                       'diaper': DiaperStatusForm,
                       'temperature': TemperatureForm,
                       'sleep': SleepForm,
                       'wake': WakeForm}
    care_taker = CareTaker.objects.get(user=request.user)

    if request.method == "GET":
        try:
            baby_id = int(request.GET['baby_id'])
            baby = Baby.objects.get(id=baby_id)
        except Baby.DoesNotExist:
            return HttpResponseServerError("No records exist!")

    if request.method == "POST":
        form = event_form_list[event_type](request.POST)
        baby_id = int(request.POST['baby_id'])
        baby = Baby.objects.get(id=baby_id)
        if form.is_valid():
            event = form.save(commit=False)
            event.baby = baby
            event.save()
            return HttpResponseRedirect('/MBF/')
    else:
        form = event_form_list[event_type]()

    if care_taker.family == baby.family:
        return render(request, 'MBF/add_event.html', {'form': form,
                                                      'baby_id': baby_id})
    else:
        raise PermissionDenied

def bottle_chart(request):
    baby_id = int(request.GET['baby_id'])
    #Step 1: Create a DataPool with the data we want to retrieve.
    event_data = \
        DataPool(
           series=
            [{'options': {
               'source': BottleFed.objects.filter(baby__id=baby_id).order_by('-event_time')[0:20]},
              'terms': [
                'event_time',
                'amount']}
             ])
    def dt_convert(dt_object):
        local_tz = pytz.timezone('America/Chicago')
        local_dt = dt_object.replace(tzinfo=pytz.utc).astimezone(local_tz)
        return local_dt.strftime('%a %I:%M %p')
        # return dt_object.strftime('%a %b %d')

    #Step 2: Create the Chart object
    cht = Chart(
            datasource = event_data,
            series_options =
              [{'options':{
                  'type': 'column',
                  'stacking': False},
                'terms':{
                  'event_time': [
                    'amount']
                  }}],
            chart_options =
              {'title': {
                   'text': 'Bottle Feeding'},
               'xAxis': {
                    'title': {
                       'text': 'Date'}},
                'yAxis': {
                    'title': {
                        'text': 'Amount (oz)'}}},
            x_sortf_mapf_mts = (None, dt_convert, False))

    #Step 3: Send the chart object to the template.
    return render(request, 'MBF/chart.html',{'chart': cht})

new_parent/MBF/templates/MBF/add_event.html
{% extends "MBF/base.html" %}
{% load bootstrap3 %}

{% block content %}

<div class="row row-offset">
<div class="col-lg-4 col-lg-offset-4">
<div class="well bs-component">
<legend>Add Event</legend>
<form action="" method="post" class="form-horizontal">
  <fieldset>
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    <input type="hidden" name="baby_id" value="{{ baby_id }}"/>

    <p class="text-center">
      <button type="submit" class="btn btn-primary ">Submit</button>
      <button type="reset" class="btn btn-default ">Reset</button>
      <a href="{% url 'MBF:MBF-dashboard' %}" class="btn btn-danger">Cancel</a>
    </p>
  </fieldset>
</form>
</div>
</div>
</div>
{% endblock %}

new_parent/MBF/templates/MBF/base.html
{% load staticfiles %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <link href="https://bootswatch.com/spacelab/bootstrap.min.css" rel="stylesheet">
  <link href="{% static 'MBF/styles/custom.css' %}" rel="stylesheet">
  {% bootstrap_javascript %}
  <title>{% block title %}M.B.F. Dashboard{% endblock %}</title>
  <link rel="icon" href="{% static 'MBF/MBF.ico' %}">
</head>

<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'MBF:MBF-dashboard' %}">Mom's Best Friend</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{% url 'MBF:create-caretaker' %}">Add a Caretaker</a></li>
              <li><a href="{% url 'MBF:create-child' %}">Add a Child</a></li>

              <!--<li class="divider"></li>-->
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <!-- <li style="padding-top: 17px; padding-bottom: 13px">User: {{ user.get_username|capfirst }}</li> -->
            <li><a href="{% url 'logout' %}">Logout {{ user.get_username|capfirst }}</a></li>
          {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">

    <div class="starter-template">
    {% block content %}{% endblock %}
    </div>

  </div>
</body>
</html>

new_parent/MBF/templates/MBF/chart.html
{% load staticfiles %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <!-- {% bootstrap_css %} -->
  <link href="https://bootswatch.com/spacelab/bootstrap.min.css" rel="stylesheet">
  {% bootstrap_javascript %}
  {% load chartit %}
  {{ chart|load_charts:"container" }}
  <title>{% block title %}M.B.F. Charts{% endblock %}</title>
  <link rel="icon" href="{% static 'MBF/MBF.ico' %}">
</head>

<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'MBF:MBF-dashboard' %}">Mom's Best Friend</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{% url 'MBF:create-child' %}">Add a Child</a></li>

              <!--<li class="divider"></li>-->
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout {{ user.get_username|capfirst }}</a></li>
          {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">

    <div class="starter-template">
    {% block content %}
    <div id='container'></div>
    {% endblock %}
    </div>

  </div>


</body>
</html>

new_parent/MBF/templates/MBF/create_baby.html
{% extends "MBF/base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="row row-offset">
<div class="col-lg-4 col-lg-offset-4">
<div class="well bs-component">
<form action="{% url 'MBF:create-child' %}" method="post" class="form-horizontal">
  <fieldset>
    <legend>Add a Child</legend>
    {% csrf_token %}
    {% bootstrap_form baby_form layout='inline' %}

    <p class="text-center">
      <button type="submit" class="btn btn-primary ">Submit</button>
      <button type="reset" class="btn btn-default ">Reset</button>
      <a href="{% url 'MBF:MBF-dashboard' %}" class="btn btn-danger">Cancel</a>
    </p>
  </fieldset>
</form>
</div>
</div>
</div>
{% endblock %}

new_parent/MBF/templates/MBF/create_caretaker.html
{% extends "MBF/base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="row row-offset">
<div class="col-lg-4 col-lg-offset-4">
<div class="well bs-component">
<form action="{% url 'MBF:create-caretaker' %}" method="post" class="form-horizontal">
  <fieldset>
    <legend>Add a Caretaker</legend>
    {% csrf_token %}
    {% bootstrap_form user_form layout='inline' %}
    {% bootstrap_form caretaker_form layout='inline' %}

    <p class="text-center">
      <button type="submit" class="btn btn-primary ">Submit</button>
      <button type="reset" class="btn btn-default ">Reset</button>
      <a href="{% url 'MBF:MBF-dashboard' %}" class="btn btn-danger">Cancel</a>
    </p>
  </fieldset>
</form>
</div>
</div>
</div>
{% endblock %}

new_parent/MBF/templates/MBF/create_user.html
{% load staticfiles %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <link href="https://bootswatch.com/spacelab/bootstrap.min.css" rel="stylesheet">
  <link href="{% static 'MBF/styles/custom.css' %}" rel="stylesheet">
  {% bootstrap_javascript %}
  {% bootstrap_messages %}
  <title>{% block title %}M.B.F. Create Account{% endblock %}</title>
  <link rel="icon" href="{% static 'MBF/MBF.ico' %}">
</head>

{% block content %}
<div class="row row-offset">
<div class="col-lg-4 col-lg-offset-4">
<div class="well bs-component">
<legend>Create an Account</legend>
<form action="{% url 'MBF:create-account' %}" method="post" class="form-horizontal">
  <fieldset>
    {% csrf_token %}
    {% bootstrap_form user_form layout='inline' %}
    {% bootstrap_form family_form layout='inline' %}
    {% bootstrap_form caretaker_form layout='inline' %}

    <p class="text-center">
      <button type="submit" class="btn btn-primary ">Submit</button>
      <button type="reset" class="btn btn-default ">Reset</button>
      <a href="{% url 'home' %}" class="btn btn-danger">Cancel</a>
    </p>
  </fieldset>
</form>
</div>
</div>
</div>

{% endblock %}

new_parent/MBF/templates/MBF/dashboard.html
{% extends "MBF/base.html" %}
{% load staticfiles %}

{% block content %}

<!-- <h1>{{ user.get_username|capfirst }}'s Dashboard</h1> -->
{% for baby in babys %}
<legend><h2>{{ baby.first_name|capfirst }}'s most recent events</h2></legend>

<div class="row">
  <div class="col-xs-4 col-md-4 text-center">
    <h3>Breast Feeding</h3>
    <img src="{% static 'MBF/breastfeeding_2.jpg' %}" alt="Breast feeding image" height="128" width="">
    {% for event in baby.get_breast_events %}
      <p>Fed from the {{ event.breast }} on {{ event.event_time|date:'l' }} at {{ event.event_time|date:'P' }}</p>
    {% empty %}
      <p>No entries</p>
    {% endfor %}
    <a href="/MBF/add-event/breast?baby_id={{ baby.id }}" class="btn btn-primary">Update</a>
  </div>

  <div class="col-xs-4 col-md-4 text-center">
    <h3>Bottle Feeding</h3>
    <img src="{% static 'MBF/feeding-bottle.png' %}" alt="Bottle image" height="" width="">
    {% for event in baby.get_bottle_events %}
      <p>Ate {{ event.amount }} oz. on {{ event.event_time|date:'l' }} at {{ event.event_time|date:'P' }}</p>
    {% empty %}
      <p>No entries</p>
    {% endfor %}
    <a href="/MBF/add-event/bottle?baby_id={{ baby.id }}" class="btn btn-primary">Update</a>
    <a href="/MBF/bottle-chart?baby_id={{ baby.id }}" class="btn btn-primary">Graph</a>
  </div>

<div class="col-xs-4 col-md-4 text-center">
  <h3>Diaper</h3>
  <img src="{% static 'MBF/baby-diaper-outline.png' %}" alt="Diaper image" height="" width="">
  {% for event in baby.get_diaper_events %}
    <p >{{ event.diaper|capfirst }} in the diaper on {{ event.event_time|date:'l' }} at {{ event.event_time|date:'P' }}</p>
  {% empty %}
    <p>No entries</p>
  {% endfor %}
  <a href="/MBF/add-event/diaper?baby_id={{ baby.id }}" class="btn btn-primary">Update</a>
</div>
</div>
<br>
<div class="row">
<div class="col-xs-4 col-md-4 text-center">
  <h3>Temperature</h3>
  <img src="{% static 'MBF/thermometer.png' %}" alt="Temperature image" height="" width="">
  {% for event in baby.get_temperature_events %}
    <p>Temperature was {{ event.temp }} on {{ event.event_time|date:'l' }} at {{ event.event_time|date:'P' }}</p>
  {% empty %}
    <p>No entries</p>
  {% endfor %}
  <a href="/MBF/add-event/temperature?baby_id={{ baby.id }}" class="btn btn-primary">Update</a>
</div>

<div class="col-xs-4 col-md-4 text-center">
  <h3>Sleep Time</h3>
  <img src="{% static 'MBF/moon-and-stars.png' %}" alt="Sleep image" height="" width="">
  {% for event in baby.get_sleep_events %}
    <p>Fell asleep on {{ event.event_time|date:'l' }} at {{ event.event_time|date:'P' }}</p>
  {% empty %}
    <p>No entries</p>
  {% endfor %}
  <a href="/MBF/add-event/sleep?baby_id={{ baby.id }}" class="btn btn-primary">Update</a>
</div>

  <div class="col-xs-4 col-md-4 text-center">
    <h3>Wake Time</h3>
    <img src="{% static 'MBF/smiling-sun.png' %}" alt="Wake image" height="" width="">
    {% for event in baby.get_wake_events %}
      <p>Woke up on {{ event.event_time|date:'l' }} at {{ event.event_time|date:'P' }}</p>
    {% empty %}
      <p>No entries</p>
    {% endfor %}
    <a href="/MBF/add-event/wake?baby_id={{ baby.id }}" class="btn btn-primary">Update</a>
  </div>
</div>
<br>
<br>
{% endfor %}

<div class="col-xs-12 col-lg-offset-2">
     <script type="text/javascript">
       	amzn_assoc_ad_type = "banner";
	amzn_assoc_marketplace = "amazon";
	amzn_assoc_region = "US";
	amzn_assoc_placement = "assoc_banner_placement_default";
	amzn_assoc_campaigns = "baby";
	amzn_assoc_banner_type = "category";
	amzn_assoc_p = "48";
	amzn_assoc_isresponsive = "false";
	amzn_assoc_banner_id = "1JYH964PEQVNKDREH182";
	amzn_assoc_width = "728";
	amzn_assoc_height = "90";
	amzn_assoc_tracking_id = "momsbestfri07-20";
	amzn_assoc_linkid = "b37b543c10490e4df7ef1c2d0197f111";
     </script>
     <script src="//z-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&Operation=GetScript&ID=OneJS&WS=1"></script>
</div>

{% endblock %}

new_parent/MBF/templates/MBF/home.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap3 %}

<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <link href="https://bootswatch.com/spacelab/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'MBF/styles/custom.css' %}" rel="stylesheet">
    {% bootstrap_javascript %}
    <title>M.B.F. Home</title>
    <link rel="icon" href="{% static 'MBF/MBF.ico' %}">
    <style>
      body {
        background-color: rgb(238, 238, 238);
      }
    </style>
  </head>
  <body>
    <div class="jumbotron ">
      <h1 class="text-center">Welcome to Mom's Best Friend</h1>
      <a href="/MBF/" class="">
        <img class="center-block" src="{% static 'MBF/MBF.png' %}" alt="Mothers Best Friend logo" height="303" width="400">
      </a>
      <div class="row-offset text-center">
        <a href="/login/" class="btn btn-primary btn-lg">Login</a>
        <a href="/MBF/create-account/" class="btn btn-primary btn-lg">Create Account</a>
      </div>
    </div>


  </body>
</html>